[package]
name = "children-audio-library"
version = "1.0.0"
authors = ["Ondrej Brinkel <info@anzui.de>"]

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
hyper = "0.11.2"
futures = "0.1.14"
hyper-staticfile = "0.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
percent-encoding = "1.0.1"
chrono = "0.4.2"
sha1 = "0.6.0"
natord = "1.0.9"
